apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-project
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: http://gitlab.example.lab/kogito-examples.git